implemented matrix for build arch, updated licence description, switched to installing rust according to redis/redis flow

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -2,8 +2,7 @@ name: redis
 adopt-info: redis
 summary: Redis is used as a database, cache and message broker. # 79 char long summary
 description: |
-  # The licence description needs to be updated to match the new licence strategy
-  Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker. |
+  Redis is source-available software, available under both the Redis Source Available License v2 (RSALv2) and the Server Side Public License v1 (SSPLv1). In-memory data structure store, used as a database, cache and message broker. |
   It supports data structures such as strings, hashes, lists, sets, sorted sets with range queries, bitmaps, hyperloglogs, geospatial indexes with radius queries and streams. |
   Redis has built-in replication, Lua scripting, LRU eviction, transactions and different levels of on-disk persistence, and provides high availability via Redis Sentinel and automatic partitioning with Redis Cluster. |
   |
@@ -73,7 +72,38 @@ parts:
       - BUILD_WITH_MODULES: "yes"
     override-build: |
       echo "BUILD_WITH_MODULES = $BUILD_WITH_MODULES"
-      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+
+      # Rust installation script
+      RUST_VERSION=1.80.1; \
+      ARCH="$$(uname -m)"; \
+      if ldd --version 2>&1 | grep -q musl; then LIBC_TYPE="musl"; else LIBC_TYPE="gnu"; fi; \
+      echo "Detected architecture: $${ARCH} and libc: $${LIBC_TYPE}"; \
+      case "$${ARCH}" in \
+        'x86_64') \
+          if [ "$${LIBC_TYPE}" = "musl" ]; then \
+            RUST_INSTALLER="rust-$${RUST_VERSION}-x86_64-unknown-linux-musl"; \
+            RUST_SHA256="37bbec6a7b9f55fef79c451260766d281a7a5b9d2e65c348bbc241127cf34c8d"; \
+          else \
+            RUST_INSTALLER="rust-$${RUST_VERSION}-x86_64-unknown-linux-gnu"; \
+            RUST_SHA256="85e936d5d36970afb80756fa122edcc99bd72a88155f6bdd514f5d27e778e00a"; \
+          fi ;; \
+        'aarch64') \
+          if [ "$${LIBC_TYPE}" = "musl" ]; then \
+            RUST_INSTALLER="rust-$${RUST_VERSION}-aarch64-unknown-linux-musl"; \
+            RUST_SHA256="dd668c2d82f77c5458deb023932600fae633fff8d7f876330e01bc47e9976d17"; \
+          else \
+            RUST_INSTALLER="rust-$${RUST_VERSION}-aarch64-unknown-linux-gnu"; \
+            RUST_SHA256="2e89bad7857711a1c11d017ea28fbfeec54076317763901194f8f5decbac1850"; \
+          fi ;; \
+        *) echo >&2 "Unsupported architecture: '$${ARCH}'"; exit 1 ;; \
+      esac; \
+      echo "Downloading and installing Rust standalone installer: $${RUST_INSTALLER}"; \
+      wget --quiet -O $${RUST_INSTALLER}.tar.xz https://static.rust-lang.org/dist/$${RUST_INSTALLER}.tar.xz; \
+      echo "$${RUST_SHA256} $${RUST_INSTALLER}.tar.xz" | sha256sum -c --quiet || { echo "Rust standalone installer checksum failed!"; exit 1; }; \
+      tar -xf $${RUST_INSTALLER}.tar.xz; \
+      (cd $${RUST_INSTALLER} && ./install.sh); \
+      rm -rf $${RUST_INSTALLER}
+
       source $HOME/.cargo/env
       mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr
       export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
